language: rust

rust: 1.35.0

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - dist: xenial
      env: RUSTUP_HOST=x86_64-unknown-linux-gnu
    - dist: xenial
      env: RUSTUP_HOST=x86_64-unknown-linux-musl
    - os: osx
      env: RUSTUP_HOST=x86_64-apple-darwin
    - os: windows
      env: RUSTUP_HOST=x86_64-pc-windows-msvc
    - os: windows
      env: RUSTUP_HOST=x86_64-pc-windows-gnu

install:
  - rustup self update
  - rustup set default-host "$RUSTUP_HOST"
  - rustup update "$TRAVIS_RUST_VERSION"
  - rustup component add clippy rustfmt
  - rustc --version --verbose
  - cargo --version --verbose
  - cargo clippy --version
  - rustfmt --version
  - |
    if [ "$TRAVIS_RUST_VERSION" = stable -a "$RUSTUP_HOST" = x86_64-unknown-linux-gnu -a "$TRAVIS_BRANCH" = master -a "$TRAVIS_PULL_REQUEST" = false ]; then
      cargo install cargo-kcov &&
      travis_retry bash -c 'cargo kcov --print-install-kcov-sh | sh' &&
      kcov --version &&
      cargo-kcov --version
    fi || true

script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-targets -- -D warnings
  - |
    if [ -f ~/.cargo/bin/cargo-kcov ]; then
      travis_retry cargo kcov --all && travis_retry bash -c 'bash <(curl -s https://codecov.io/bash)' ||
      cargo test --all
    else
      cargo test --all
    fi

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master
